### ISSUE TITLE
Integration with Gitter

### ISSUE THREAD

**Issue by laughedelic** [mertkahyaoglu/atom-chat#3]
Hi! This plugin looks very nice. Have you thought about using [Gitter.im](http://gitter.im) infrastructure for it? There was [one attempt](https://github.com/Glavin001/atom-gitter), but it got abandoned..

**Comment by mertkahyaoglu** [comment]
Thanks for sharing your thoughts :+1:  I will look into it and let you know how it's going

**Comment by laughedelic** [comment]
So what was your decision in the end?

**Comment by mertkahyaoglu** [comment]
I decided to leave it as it is because currently I can't find time for the project :grin: . I think this will be the last version of it. Simple and working..
